review of options & variables

diff --git a/libexec/bash-utils-core b/libexec/bash-utils-core
--- a/libexec/bash-utils-core
+++ b/libexec/bash-utils-core
@@ -34,11 +34,11 @@
 
 # use aliases
 shopt -s expand_aliases
-# export all modified vars (set -a)
+# export all defined variables (set -a)
 set -o allexport
-# match the POSIX 1003.2 standard ; see <http://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html>
+# force Bash to conform to the POSIX 1003.2 standard ; see <http://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html>
 set -o posix
-# exit if a command has a non-zero status (set -e)
+# abort script at first command with a non-zero status (set -e)
 set -o errexit
 # do not mask pipeline's errors
 set -o pipefail
@@ -46,8 +46,10 @@ set -o pipefail
 set -o errtrace
 # trap on DEBUG and RETURN are inherited by shell functions (set -T)
 set -o functrace
-## throw error on unset variable usage (set -u)
+# throw error on unset variable usage (set -u)
 set -o nounset
+# prevent overwriting of files by redirection (set -C - may be overridden by `... >| file`)
+set -o noclobber
 
 ## for dev usage: debug commands before to execute them (set -x)
 #set -o xtrace
@@ -731,22 +733,30 @@ set_env_array BASH_UTILS_ARGS BASH_UTILS_ARGS[@]
 
 ## globals
 
+# name of current called script
 CMD_PROG="$(basename "$0")"
+# real path of current called script
 CMD_ROOT="$(abs_dirname "$0")"
+# OS name
 CMD_OS="$(uname)"
-CMD_HOST="$(hostname -f)"
-CMD_USER="$(id -un)"
+# original working directory
 CMD_CWD="$(pwd)"
+# original process ID
 CMD_PID="$$"
+# original CLI call
 CMD_CALL_ORIGINAL="$0 $*"
-readonly  CMD_PROG CMD_ROOT CMD_OS CMD_HOST CMD_USER CMD_CWD CMD_PID CMD_CALL_ORIGINAL
-export CMD_CALL=''
+readonly  CMD_PROG CMD_ROOT CMD_OS CMD_CWD CMD_PID CMD_CALL_ORIGINAL
+# final CLI call (eventually rebuilt by the `rearrange_options()` function)
+export CMD_CALL="$CMD_CALL_ORIGINAL"
+# name of current module if one is called
 export CMD_MODULE=''
+# content of a piped previous command (populated by the `read_from_pipe()` function)
 export PIPED_INPUT=''
+# list of available modules
+declare -a MODULES_AVAILABLE=()
 
 # load library & modules on PRELOAD
 source "$BASH_UTILS_ROOT"/bash-utils-lib
-declare -a MODULES_AVAILABLE=()
 export PRELOAD=true
 for f in "$BASH_UTILS_MODULES"/*; do
     if [ -f "$f" ] && [ -x "$f" ]; then
@@ -794,8 +804,9 @@ export CMD_LOGFILE
 
 # special debug table
 declare -ax TO_DEBUG=(
-    CMD_PROG CMD_ROOT CMD_HOST CMD_USER CMD_CWD CMD_PID CMD_OS
-    CMD_CALL VERBOSE QUIET DEBUG FORCE DRY_RUN
+    HOSTNAME MACHTYPE LANG SHELL BASH_VERSION SHELLOPTS USER UID
+    CMD_PROG CMD_ROOT CMD_CWD CMD_PID CMD_OS CMD_LOGFILE
+    CMD_CALL_ORIGINAL CMD_CALL VERBOSE QUIET DEBUG FORCE DRY_RUN
 )
 set_env_array TO_DEBUG TO_DEBUG[@]
 
