new GNU like error string

diff --git a/libexec/bash-utils-core b/libexec/bash-utils-core
--- a/libexec/bash-utils-core
+++ b/libexec/bash-utils-core
@@ -148,8 +148,14 @@ die()
 # usage: `error [string='unknown error'] [status=1]`
 error()
 {
-    {   echo "error: ${1:-unknown error}"
-        $VERBOSE && echo "# in ${BASH_SOURCE[1]##*/} at line ${BASH_LINENO[0]}";
+    local errstr
+    if $VERBOSE; then
+        errstr="$(gnu_error_string "${1:-unknown error}")"
+    else
+        errstr="${1:-unknown error}"
+    fi
+    {   echo '---'
+        echo "error: ${errstr}"
         echo '---'
         usage_info
     } >&2
@@ -168,6 +174,22 @@ find_module()
     else
         return 1
     fi
+}
+
+# must echoes something like 'sourcefile:lineno: message'
+# see <https://www.gnu.org/prep/standards/html_node/Errors.html>
+# usage: `gnu_error_string <string> [filename=BASH_SOURCE[2]] [funcname=FUNCNAME[2]] [line=BASH_LINENO[1]]`
+gnu_error_string()
+{
+    local errorstr=''
+    local _source="${2:-${BASH_SOURCE[2]}}"
+    [ -z "$_source" ] || errorstr+="${_source}:";
+    local _func="${3:-${FUNCNAME[2]}}"
+    [ -z "$_func" ] || errorstr+="${_func}:";
+    local _line="${4:-${BASH_LINENO[1]}}"
+    [ -z "$_line" ] || errorstr+="${_line}:";
+    echo "${errorstr} ${1}"
+    return 0
 }
 
 # write help string to STDERR & exit
